### ISSUE TITLE
Less than 3-sigma detections STILL being recorded as first detection points 

### ISSUE THREAD

**Issue by smarttgit** [genghisken/ps1#94]
I thought we sorted this 

I see many examples in the good list where the "first" detection is a <3 sigma measurement and it is still being recorded as the first detection. 

https://star.pst.qub.ac.uk/sne/atlas4/lightcurveforced/1174801880244600600/

This is not being propagated to the marshall (good) but still is in the ATLAS pages

**Comment by genghisken** [comment]
Dave's code dynamically alters the forced photometry output as read from here.  I left the raw (1sigma) production of low SNR data in there so that people and lightcurve code (including on the ATLAS pages) could make up their own mind how to process the data.  I've provided Morgan and Armin with information on how to read the low SNR data (and reproduce Nsigma limits if necessary), but if you want me to stop actually producing it, that's fine.  If I do this, it will mean that in future, if we want to look for marginal detections, we will need to rerun the forced photometry for that object.

**Comment by genghisken** [comment]
Alternatively I could leave the 1sigma SNR data in the database and alter the CSV rendering code to only produce 3sigma.

**Comment by genghisken** [comment]
I think we're happy with the current way that the marshall reads the ATLAS forced photometry.
