### ISSUE TITLE
Real object thrown into garbage before stamps  - check it will pass the new cuts

### ISSUE THREAD

**Issue by smarttgit** [genghisken/ps1#98]
This is in the garbage without getting stamps 

But it is a real object (AT2018avd) 

https://star.pst.qub.ac.uk/sne/atlas4/candidate/1140251180042517700/

The cuts must be adjusted to allow this through - psc and pno are very low. PTR + PVR are high. 

This needs considered as we redefine the cuts

**Comment by genghisken** [comment]
This was thrown away because I still have a quarantine on all objects in the bad chip area on the MLO detector.  We removed it temporarily but I reinstated it when we were overwhelmed with junk (end of January I think).  We need to revisit the objects flagged in this area again. And even if not, I will alter the code to NOT ditch objects, but not promote them either unless we get good detections elsewhere on the chip or on HKO.
